services:
  cineplex-rigaud:
    build: .
    container_name: cineplex-rigaud
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: false
    volumes:
      - ~/media/movies:/mnt/media/movies:ro
      - ~/media/tv:/mnt/media/tv:ro
      - cache:/mnt/cache
    restart: unless-stopped

volumes:
  cache:
